### ISSUE TITLE
-vrmode oculus issues (MP Extensions / Hide only in VR)

### ISSUE THREAD

**Issue by SenkuwuWasTaken** [kinsi55/CS_BeatSaber_FocusMod#2]

**Comment by kinsi55** [comment]
Could you provide more details? I just downloaded Multiplayer extensions, opened a server and I could start a custom song just fine.

**Comment by SenkuwuWasTaken** [comment]
huh... i was figuring out why i couldnt load into multi songs and ended up deleteing every mod one by one and it worked as soon as i got rid of focusmod, maybe its related to me being on "-vrmode oculus"?

**Comment by kinsi55** [comment]
Shouldnt be, do you have any other multiplayer related mods installed other than multiplayer extensions? Were you hosting the server or did you join it? Was it a map that you already had?

**Comment by SenkuwuWasTaken** [comment]
it happened no matter what, even if i was in a lobby by myself. and i tried it with only core mods and multi extension.

**Comment by kinsi55** [comment]
Thats Weird. Do you have the latest version of FocusMod? (Updated today) as well as MP extensions? Also what exacly happens instead of loading into the song? Does the game freeze / crash? Does it just infinitely load?

**Comment by SenkuwuWasTaken** [comment]
yes i have all the most recent versions. the game goes into an indefinite black screen once the game "starts" a song.

**Comment by kinsi55** [comment]
I just tried it again with all combinations of HUD options I'm presented in the lobby and couldnt reproduce your issue.

Do you use Counters+? If so, any thirdparty counters that you have enabled in it? What combinations of hud options do you have on / off in the lobby?

Additonally, what is your FocusMod configuration?

**Comment by SenkuwuWasTaken** [comment]
i dont have counters+, and tried every combination of hud options except disabling it altogether. i will try testing it again once ive finished this multi.

**Comment by kinsi55** [comment]
Just removed Counters+ and tried the same thing again, also having tried "only hide in VR" on / off, still able to load into custom songs just fine. Its starting to look like it must be one of your other mods possibly conflicting.

You can see the list of mods that I use [here](https://github.com/kinsi55/CS_BeatSaber_GottaGoFast#benchmark--comparison) and could possibly try and see if removing others you use resolves the issue.

**Comment by SenkuwuWasTaken** [comment]
i have tried with only these mods and it still doesn't work, i have also noticed the hud doesn't disappear at all with "only hide in vr" on. if you're not testing on oculus, i'm now sure thats the reason it works for you. 
![image](https://user-images.githubusercontent.com/73919665/104536551-26fdcc80-567d-11eb-8efe-fdca8e8c54a9.png)

**Comment by kinsi55** [comment]
I am indeed not testing on Oculus and dont own any Oculus headset so I have no easy way to test this, I know various people who play on an Oculus device tho, I will see if I can get one of them to try and see if they are able to replicate it and will let you know about the results.

>i have also noticed the hud doesn't disappear at all with "only hide in vr" on

That is in Multiplayer? I quite honestly never tested multiplayer, so that is entirely possible, it should work fine in solo tho assuming there is no weird Oculus quirks.

**Comment by SenkuwuWasTaken** [comment]
no, that's in singleplayer.

**Comment by kinsi55** [comment]
Alright, I'll try to look into these things, thanks for making me aware.

**Comment by Hexnet111** [comment]
> huh... i was figuring out why i couldnt load into multi songs and ended up deleteing every mod one by one and it worked as soon as i got rid of focusmod, maybe its related to me being on "-vrmode oculus"?

Same thing happened to me, although I didn't know what caused it. Oh well until its fixed I guess I'm gonna have to remove the focus mod.

**Comment by Hexnet111** [comment]
> huh... i was figuring out why i couldnt load into multi songs and ended up deleteing every mod one by one and it worked as soon as i got rid of focusmod, maybe its related to me being on "-vrmode oculus"?

I got the same thing happening to me, although I don't know if its caused by the focus mod yet.

**Comment by kinsi55** [comment]
@Draegon366 @Hexnet111 Seeing as the plugin does not really work in Multiplayer anyways (And I dont think its that important there to begin with) I've made a small change which explicitly disables it for MP. Could you try and see if this resolves the issue?

[FocusMod.zip](https://github.com/kinsi55/CS_BeatSaber_FocusMod/files/5815086/FocusMod.zip)

**Comment by kinsi55** [comment]
Had somebody install MP extensions and FocusMod (Official release, not this modified one), he is on -vrmode oculus and could load into custom songs just fine as well, so it has to be some sort of configuration issue.

**Comment by SenkuwuWasTaken** [comment]
that is very strange, but the modified dll does work.

**Comment by kinsi55** [comment]
Alright, I guess I'll release that as an update once I figured out the hide in vr issue. Thanks for the feedback.

**Comment by SenkuwuWasTaken** [comment]
"hide only in vr" now seems to be properly hiding it, but both inside and out of vr. I tested this with every combination of focusmod settings and it didn't change anything.

**Comment by kinsi55** [comment]
> but both inside and out of vr 

Are you using the official Camera Plus or my modified one? Either way, it hiding in both is a result of camera plus. I'll try to find a fix.

**Comment by kinsi55** [comment]
Released https://github.com/kinsi55/CS_BeatSaber_FocusMod/releases/tag/v0.1.3

Should address all issues, thanks for the help :)
